Repository Techtonica/curriculum, pull requests merged in 2020-03, with the labels that each got.

#1223 Update enzyme-testing with Testing Automation link.md
  testing-and-tdd/enzyme-testing.md
Labels: gssoc20

#1225 Added relative links
  CONTRIBUTING.md
  README.md
  _templates/topic-outline.md
  api/twilio-api.md
  best-practice-in-development/best-practice-in-client-side-development.md
  command-line/command-line-interface.md
  command-line/vim.md
  css/css.md
  css/reset-css.md
  data-structures/linked-lists.md
  databases/mongo-db.md
  databases/mongoose.md
  databases/relational-databases.md
  databases/sql-1.md
  databases/sql-2.md
  databases/sql.md
  html/html.md
  javascript/javascript-6-object-literals.md
  javascript/javascript-7-oop.md
  jquery/jquery.md
  objectives/0.md
  objectives/1.md
  objectives/10.md
  objectives/2.md
  objectives/3.md
  objectives/4.md
  objectives/5.md
  objectives/6.md
  objectives/7.md
  professionalism/LinkedIn.md
  projects/data-structures-algorithms-assessment.md
  projects/data-structures-algorithms-sprint.md
  projects/eventonica/eventonica-react.md
  projects/final-project/final-project.md
  projects/final-project/planning-your-project.md
  projects/minimal-api-project.md
  projects/recipe-page/phase-1-html-prompt.md
  projects/recipe-page/phase-2-css-prompt.md
  roles-in-tech/data-science.md
  roles-in-tech/machine-learning.md
Labels: EASY, gssoc20

#1244 Closes issue #1201 outline for code liniting + eslint instructions
  javascript/eslint.md
  linting/code-linting-eslint.md
Labels: MEDIUM, gssoc20, pending-pr-revisions

#1233 Checked whether let and const are used properly and then changed accordingly
  functional-programming/FP.md
  javascript/javascript-7-oop.md
  javascript/javascript-maps.md
  objectives/week-6-assessment.md
  prework/week2LoopsExercise.js
  projects/Eventful-API-test-page/eventfulAPI.js
  runtime-complexity/runtime1-analyzing.js
  testing-and-tdd/mocha-testing.md
Labels: EASY, gssoc20, pending-pr-revisions

#1238 Renamed all JavaScript lessons and updated links to them.
  README.md
  api/apis-and-json.md
  data-structures/deque.md
  data-structures/intro-to-data-structures.md
  data-structures/linked-lists.md
  data-structures/queues.md
  data-structures/trees.md
  datetime/datetime.md
  functional-programming/FP.md
  javascript/javascript-1-variables.md
  javascript/javascript-2-array-functions.md
  javascript/javascript-3-conditionals.md
  javascript/javascript-4-loops.md
  javascript/javascript-5-switch.md
  javascript/javascript-6-object-literals.md
  javascript/javascript-7-oop.md
  javascript/javascript-8-regex.md
  javascript/javascript-9-async.md
  javascript/javascript-maps.md
  recursion/recursion.md
Labels: EASY, gssoc20, pending-pr-revisions

#1242 Added Elective Lesson on Angular
  electives/Angular/angular.md
Labels: MEDIUM, gssoc20, pending-pr-revisions

#1260 Completed issue #1196 for verifying slideshows based on #1195
  css/BEM-style.md
Labels: MEDIUM, gssoc20

#1237 Added Github Folder and updated links related to it.
  README.md
  _templates/topic-outline.md
  agile-development/scrum.md
  command-line/env.md
  git/basic-gitignore.png
  git/git-version-control-part2.md
  git/git-version-control.md
  git/github-collaboration.md
  git/github-storage.md
  git/gitignore.md
  oauth/o-auth.md
  open-source/open-source.md
  projects/recipe-page/phase-1-html-prompt.md
  projects/recipe-page/phase-2-css-prompt.md
  projects/recipe-page/phase-3-bootstrap-prompt.md
Labels: BEGINNER, gssoc20, pending-pr-revisions

#1272 Add mini-lesson on destructuring
  javascript/destructuring.md
Labels: MEDIUM, gssoc20, pending-round-2-revisions

#1252 fixes issue #1208:remove references to mongodb
  databases/installing-postgresql.md
  express-js/server-side-project.md
  objectives/9.md
  projects/final-project/final-project.md
Labels: EASY, gssoc20, pending-round-2-revisions

#1265 created folder web and moved specified lessons
  README.md
  agile-development/scrum.md
  api/apis-and-json.md
  best-practice-in-development/best-practice-in-client-side-development.md
  career/interviewing/technical-interviewing.md
  data-visualization/data-visualization.md
  react-js/react.md
  sass/sass.md
  seo/seo.md
  ui-ux-design/ui-ux-design.md
  web-patterns/web-patterns.md
  web/BEM-style.md
  web/accessibility.md
  web/ajax.md
  web/bootstrap.md
  web/css.md
  web/html.md
  web/jquery-programming-fundamentals/index.html
  web/jquery-programming-fundamentals/static/js/myScript.js
  web/jquery.md
  web/media-queries.md
  web/reset-css.md
Labels: EASY, gssoc20, pending-pr-revisions

#1299 Fixed broken link in Hash Table Topic Outline
  data-structures/hash-tables.md
Labels: BEGINNER, gssoc20

#1267 Changed var into const and let as required
  api/http-request-practice.md
  application workshops/workshop-1.md
  data-structures/linked-lists.md
  data-structures/stack.md
  electives/mocha-testing.md
  javascript/javascript-6-object-literals.md
  javascript/javascript-maps.md
  node-js/node-lab-exercise-part-1.md
  oauth/authorization.md
  prework/week1ConditionalsExercise.js
  prework/week1VariablesExercise.js
  refactoring/refactoring.md
  runtime-complexity/runtime.js
  runtime-complexity/runtime1-analyzing.js
  testing-and-tdd/jasmine-pair-activity.js
  testing-and-tdd/testing-and-tdd.md
  web/ajax.md
  writing-readable-code/writing-readable-code.md
Labels: Complete, EASY, gssoc20

#1266 Fixes #1264 - Find and fix link for Assessment 9 objectives
  objectives/9.md
Labels: BEGINNER, gssoc20, pending-pr-revisions

#1258 CSS in reactJs with Bootstrap
  react-js/styling-react.md
Labels: HARD, gssoc20, pending-round-2-revisions

#1261 Simplify and Modernize AJAX Lesson
  web/ajax.md
Labels: HARD, gssoc20, pending-round-2-revisions

#1283 fix: update data visualization section
  data-visualization/data-visualization.md
Labels: EASY, gssoc20, pending-pr-revisions

#1288 Changed code into JS
  algorithms/sorting.md
Labels: EASY, gssoc20, pending-pr-revisions

#1305 added common technical interview questions
  career/interviewing/technical-interviewing.md
Labels: EASY, gssoc20, pending-pr-revisions

#1307 Replaced 4 Codecademy Pro links with a free online resource
  command-line/command-line-interface.md
  javascript/javascript-9-async.md
  sass/sass.md
  web/jquery.md
Labels: EASY, gssoc20

#1292 Updated http-request-practice.md
  api/http-request-practice.md
Labels: BEGINNER, gssoc20, pending-round-2-revisions

#1300 Proofread javascript/eslint.md
  javascript/eslint.md
Labels: EASY, gssoc20, pending-round-2-revisions

#1263 Move all on-boarding lessons into an onboarding folder
  README.md
  api/apis-and-json.md
  career/interviewing/whiteboarding.md
  career/resume-writing.md
  career/roles-in-tech/dev-ops.md
  career/roles-in-tech/roles-in-tech.md
  command-line/env.md
  debugging/debugging.md
  dev-tools/command-line-advanced.md
  dev-tools/command-line-interface.md
  dev-tools/dot-profile.md
  dev-tools/keyboard-shortcuts.md
  dev-tools/operating-systems.md
  dev-tools/vim.md
  dev-tools/vscode.md
  git/git-version-control.md
  git/github-storage.md
  javascript/eslint.md
  javascript/javascript-1-variables.md
  networking-computing/how-the-internet-works.md
  networking-computing/intro-to-dns-ip.md
  onboarding/YCLA_LessonPlan_v10.pdf
  onboarding/asking-good-questions.md
  onboarding/ergonomics.md
  onboarding/learning-to-learn.md
  onboarding/pair-programming.md
  onboarding/professionalism.md
  onboarding/tech-industry-tips.md
  projects/minimal-api-project.md
  projects/recipe-page/phase-1-html-prompt.md
  projects/recipe-page/phase-2-css-prompt.md
  projects/recipe-page/phase-3-bootstrap-prompt.md
  reading-and-writing-documentation/documentation.md
  seo/seo.md
  testing-and-tdd/testing-and-tdd.md
Labels: EASY, gssoc20, pending-round-2-revisions

#1313 Fixed links in README.md (#1282)
  README.md
Labels: BEGINNER, gssoc20
