Repository Techtonica/curriculum, pull requests merged in 2020-05, with the labels that each got.

#1333 Feature/react part2
  react-js/react-part-2.md
Labels: HARD, gssoc20, pending-round-2-revisions

#1348 Fix/1217 create mocking lesson
  testing-and-tdd/integration-testing.md
  testing-and-tdd/mocking-and-abstraction.md
Labels: MEDIUM, gssoc20, pending-alina

#1347 Created react-components-and-hierarchies.md
  react-js/react-components-and-hierarchies.md
Labels: EASY, gssoc20, pending-decision, pending-pr-revisions

#1310 Revise and simplify React Part 1 Lesson
  react-js/react.md
Labels: MEDIUM, gssoc20, pending-bill, pending-round-2-revisions

#1360 Line 81 rectified and grammatical mistakes cleared
  react-js/react-part-2.md
Labels: EASY, gssoc20

#1353 Add lesson on HTML forms
  web/html-forms.md
Labels: MEDIUM, gssoc20, pending-round-2-revisions

#1365 Fix links in Deploying to Heroku outline
  README.md
  deploying/deploying-to-heroku.md
  node-js/node-js.md
Labels: BEGINNER, gssoc20

#1370 Added js-dom-methods.md Fixes #1367
  web/js-dom-methods-walkthrough/index.html
  web/js-dom-methods-walkthrough/static/script.js
  web/js-dom-methods.md
Labels: MEDIUM, gssoc20

#1356 Update deploying.md
  deploying/Deploying.md
Labels: MEDIUM, gssoc20, pending-round-2-revisions

#1345 adds the Spread-Operator file
  javascript/Spread_operator.md
Labels: MEDIUM, gssoc20, pending-round-2-revisions

#1368 Updated html-forms.md
  web/html-forms.md
Labels: BEGINNER, gssoc20, pending-bill

#1326 Move lessons to electives folder
  CONTRIBUTING.md
  README.md
  career/roles-in-tech/data-science.md
  electives/1_intro_to_backend.md
  electives/angular.md
  electives/data-visualization.md
  electives/databases/database-migrations.md
  electives/databases/mongo-db.md
  electives/databases/mongoose.md
  electives/memoization.md
  electives/mobile-development.md
  electives/oauth/authorization.md
  electives/oauth/o-auth.md
  electives/optimization/optimization.md
  electives/optimization/optimizing-your-react-node-project.md
  electives/python.md
  electives/sass.md
  electives/web-patterns.md
  projects/eventonica/eventonica-part5-express-backend.md
  projects/mongo-assessment.md
  web/BEM-style.md
  web/css.md
Labels: MEDIUM, gssoc20, pending-alina

#1374 Added benefits of OOP in JS - #1269 resolved
  javascript/javascript-7-oop.md
Labels: EASY, gssoc20

#1373 Adds the React file
  javascript/JavaScript-React-Modularity.md
  javascript/React_JavaScript.md
Labels: EASY, gssoc20
