Repository Techtonica/curriculum, pull requests merged in 2020-04, with the labels that each got.

#1280 Add cheatsheet for common JS functions
  CONTRIBUTING.md
  README.md
  javascript/common-functions-cheatsheet.md
Labels: MEDIUM, gssoc20, pending-round-2-revisions

#1291 fixes issue #1240:Double-check BEM & md syntax, fix typos & wording in outline
  web/BEM-style.md
Labels: EASY, gssoc20, pending-round-2-revisions

#1311 Correction of slides: issue 1198
  javascript/eslint.md
Labels: EASY, gssoc20, pending-pr-revisions

#1245 Add Employees exercise for Recursion chapter
  recursion/pnr-hierarchy.png
  recursion/recursion.md
Labels: not-for-gssoc

#1192 Add node.js fundamentals study link
  node-js/node-js.md
Labels: not-for-gssoc, pending-pr-revisions

#1324 final changes made to apprenticeship-prep folder
  README.md
  apprenticeship-prep/ethics.md
  apprenticeship-prep/financial-literacy.md
  apprenticeship-prep/navigating-new-codebases.md
  apprenticeship-prep/socioeconomic-differences.md
  apprenticeship-prep/underrepresented-in-tech.md
  career/roles-in-tech/machine-learning.md
Labels: EASY, gssoc20, pending-response

#1330 fix: add homebrew installation steps
  dev-tools/command-line-advanced.md
  git/git-version-control.md
  node-js/node-lab-exercise-part-1.md
Labels: MEDIUM, gssoc20, pending-pr-revisions

#1325 Updated the files in eventonica
  README.md
  projects/eventonica/README.md
  projects/eventonica/eventonica-part7-react.md
  projects/mern-pern-project.md
Labels: BEGINNER, gssoc20, pending-pr-revisions

#1323 Create Living in Open Workspaces.md
  workplace/Living in Open Workspaces.md
Labels: MEDIUM, gssoc20, pending-round-2-revisions

#1317 Modified to reflect Mac's new default shell, zsh
  dev-tools/command-line-advanced.md
  dev-tools/command-line-interface.md
  dev-tools/dot-profile.md
Labels: MEDIUM, hackathon, not-for-gssoc, pending-round-2-revisions

#1344 New lesson: Career - Working and Collaborating Remotely
  career/working-and-collaborating-remotely.md
Labels: pending-pr-revisions
